# Authorize.Net Configuration
# Replace with your sandbox/production credentials
authorizenet.api-login-id=9Y2RvkB5Md
authorizenet.transaction-key=88c8r7E9L2W8fR8x
authorizenet.client-key=97nx7W9raYeayg5vTdErTwWk7dp3xEE76wSTfzDUUsN5dnP7J8X7EXcZBG9kNhv9

# Environment: SANDBOX or PRODUCTION
authorizenet.environment=SANDBOX

# Server
server.port=8080
spring.thymeleaf.cache=false
